### ISSUE TITLE
JsonMappingException

### ISSUE THREAD

**Issue by edvorg** [zapodot/jackson-databind-java-optional#4]
Hi. Here are minimal example.

```java
public class JavaOptionalModuleTest {

    public class Inner {
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Inner inner = (Inner) o;

            return integer.equals(inner.integer);

        }

        public Inner() {

        }

        public Inner(Optional<Integer> integer) {
            this.integer = integer;
        }

        @Override
        public int hashCode() {
            return integer.hashCode();
        }

        @JsonProperty
        public Optional<Integer> integer = Optional.empty();
    }

    public class OptionalContaining {
        public OptionalContaining() {

        }

        public OptionalContaining(Optional<Inner> inner) {
            this.inner = inner;
        }

        @JsonProperty
        public Optional<Inner> inner = Optional.empty();

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            OptionalContaining that = (OptionalContaining) o;

            return inner.equals(that.inner);
        }

        @Override
        public int hashCode() {
            return inner.hashCode();
        }
    }

    @Test
    public void testDeserialization() throws IOException {
        ObjectMapper mapper = new ObjectMapper().registerModule(new JavaOptionalModule());
        mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        assertEquals(new OptionalContaining(Optional.of(new Inner(Optional.of(7)))),
            mapper.readValue("{\"inner\":{\"integer\":7}}", OptionalContaining.class));
    }
}
```

I get an exception.

```
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.zeptolab.zombies.commons.JavaOptionalModuleTest$OptionalContaining]: can not instantiate from JSON object (need to add/enable type information?)
 at [Source: java.io.StringReader@6e20b53a; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1078)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:268)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098)
	at com.zeptolab.zombies.commons.JavaOptionalModuleTest.testDeserialization(JavaOptionalModuleTest.java:88)
```

What I'm doing wrong?

Edward.

**Comment by edvorg** [comment]
There problem was in using non static inner classes. Solved.
